degreebuilder/grails-app/domain/degreebuilder/DegreeType.groovy
package degreebuilder

/**
 * DegreeTYPE
 * A domain class describes the data object and it's mapping to the database
 */
class DegreeType {

	Long	id
	Long	version
	String  code
    String  desc
	Date	dateCreated
	Date	lastUpdated
	
	static mapping = {
	sort "code"
	   version false
	   table 'degree_type'
	   columns{
			   code column: 'code'
			   desc column: 'description'
			   dateCreated column: 'date_created'
			   lastUpdated column: 'last_updated'
	   }
	
	   id generator:'sequence', params:[sequence:'course_id_sequence']
	}
			  
	static constraints = {
		code(nullable: true, maxsize: 8)
		desc(nullable: true, maxSize: 80)
		dateCreated(nullable: true)
		lastUpdated(nullable: true)
	}
	
	/*
	 * Methods of the Domain Class
	 */
	@Override	// Override toString for a nicer / more descriptive UI
	public String toString() {
		return "${code}";
	}
}

degreebuilder/grails-app/views/admin/_degreeBlockTypeForm.gsp
<%@ page import="degreebuilder.DegreeBlockType" %>
			<div class="control-group fieldcontain ${hasErrors(bean: degreeBlockTypeInstance, field: 'name', 'error')} required">
				<label for="Name" class="control-label"><g:message code="degreeBlockType.name.label" default="Name" /></label>
				<div class="controls">
					<g:textField name="name" maxlength="50" value="${degreeBlockTypeInstance?.name}"/>
					<span class="help-inline">${hasErrors(bean: degreeBlockTypeInstance, field: 'name', 'error')}</span>
				</div>
			</div>
			
			<div class="control-group fieldcontain ${hasErrors(bean: degreeBlockTypeInstance, field: 'displayGroup', 'error')} required">
				<label for="displayGroup" class="control-label"><g:message code="degreeBlockType.displayGroup.label" default="Display Group" /><span class="required-indicator">*</span></label>
				<div class="controls">
					<g:field type="number" name="displayGroup" required="" value="${degreeBlockTypeInstance.displayGroup}"/>
					<g:select name="displayGroup" value="${degreeBlockTypeInstance.displayGroup}" from="${[DegreeBlockTypeGroup.MAJOR_SPECIFIC_GEN_ED,DegreeBlockTypeGroup.ELECTIVES]}" noSelection="${['':'-Choose Degree Type-']}"/>
					<span class="help-inline">${hasErrors(bean: degreeBlockTypeInstance, field: 'displayGroup', 'error')}</span>
				</div>
			</div>

			<div class="control-group fieldcontain ${hasErrors(bean: degreeBlockTypeInstance, field: 'displaySeqno', 'error')} required">
				<label for="displaySeqno" class="control-label"><g:message code="degreeBlockType.displaySeqno.label" default="Display Seqno" /><span class="required-indicator">*</span></label>
				<div class="controls">
					<g:field type="number" name="displaySeqno" required="" value="${degreeBlockTypeInstance.displaySeqno}"/>
					<span class="help-inline">${hasErrors(bean: degreeBlockTypeInstance, field: 'displaySeqno', 'error')}</span>
				</div>
			</div>

degreebuilder/grails-app/views/admin/_degreeTypeForm.gsp
<%@ page import="degreebuilder.DegreeType" %>

	<div class="control-group fieldcontain ${hasErrors(bean: degreeTypeInstance, field: 'code', 'error')} ">
		<label for="code" class="control-label"><g:message code="degreeType.code.label" default="Code" /></label>
		<div class="controls">
			<g:textField name="code" value="${degreeTypeInstance?.code}"/>
			<span class="help-inline">${hasErrors(bean: degreeTypeInstance, field: 'code', 'error')}</span>
		</div>
	</div>

	<div class="control-group fieldcontain ${hasErrors(bean: degreeTypeInstance, field: 'desc', 'error')} ">
		<label for="desc" class="control-label"><g:message code="degreeType.desc.label" default="Desc" /></label>
		<div class="controls">
			<g:textField name="desc" maxlength="80" value="${degreeTypeInstance?.desc}"/>
				<span class="help-inline">${hasErrors(bean: degreeTypeInstance, field: 'desc', 'error')}</span>
		</div>
	</div>

degreebuilder/grails-app/views/admin/admin.gsp
<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'degree.label', default: 'Degree')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>

<body>
<div id="tabs">
  <ul>
    <li><a href="${createLink(controller: 'degreeType', action: 'list')}">Degree Types</a></li>
    <li><a href="${createLink(controller: 'degreeBlockType', action: 'list')}">Degree Block Types</a></li>
<%--    <li><a href="${createLink(controller: 'tabcomponent', action: 'search')}">Search</a></li>--%>
<%--    <li><a href="${createLink(controller: 'tabcomponent', action: 'result')}">Result</a></li>--%>
  </ul>
</div>
testing admin gsp
</body>
</html>

degreebuilder/grails-app/views/admin/createDegreeBlockType.gsp
<%@ page import="degreebuilder.DegreeBlockType" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'degreeBlockType.label', default: 'DegreeBlockType')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>

<body>

<section id="create-degreeBlockType" class="first">

	<g:hasErrors bean="${degreeBlockTypeInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${degreeBlockTypeInstance}" as="list" />
	</div>
	</g:hasErrors>
	
	<g:form action="save" class="form-horizontal" >
		<fieldset class="form">
			<g:render template="degreeBlockTypeForm"/>
		</fieldset>
		<div class="form-actions">
			<g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
            <button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
		</div>
	</g:form>
	
</section>
		
</body>

</html>

degreebuilder/grails-app/views/admin/createDegreeTypes.gsp
<%@ page import="degreebuilder.Degree" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'degree.label', default: 'Degree')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>

<body>

<section id="create-degree-type" class="first">
	<g:hasErrors bean="${degreeTypeInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${degreeTypeInstance}" as="list" />
	</div>
	</g:hasErrors>

	<g:form method="post" class="form-horizontal" >
		<g:hiddenField name="id" value="${degreeTypeInstance?.id}" />
		<g:hiddenField name="version" value="${degreeTypeInstance?.version}" />
		<fieldset class="form">
			<g:render template="degreeTypeForm"/>
		</fieldset>
		<div class="form-actions">
			<g:actionSubmit class="btn btn-primary" action="save" value="${message(code: 'default.button.save.label', default: 'Save')}" />
            <button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
		</div>
	</g:form>
</section>
</body>
</html>

degreebuilder/grails-app/views/admin/editDegreeBlockType.gsp
<%@ page import="degreebuilder.DegreeBlockType" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'degreeBlockType.label', default: 'DegreeBlockType')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>

<body>

<section id="edit-degreeBlockType" class="first">

	<g:hasErrors bean="${degreeBlockTypeInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${degreeBlockTypeInstance}" as="list" />
	</div>
	</g:hasErrors>

	<g:form method="post" class="form-horizontal" >
		<g:hiddenField name="id" value="${degreeBlockTypeInstance?.id}" />
		<g:hiddenField name="version" value="${degreeBlockTypeInstance?.version}" />
		<fieldset class="form">
			<g:render template="degreeBlockTypeForm"/>
		</fieldset>
		<div class="form-actions">
			<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
			<g:actionSubmit class="btn btn-danger" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            <button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
		</div>
	</g:form>

</section>
			
</body>

</html>

degreebuilder/grails-app/views/admin/editDegreeTypes.gsp
<%@ page import="degreebuilder.DegreeType" %>
<!doctype html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'degreeType.label', default: 'DegreeType')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>

<body>
<section id="edit-degreeType" class="first">
	<g:hasErrors bean="${degreeTypeInstance}">
	<div class="alert alert-error">
		<g:renderErrors bean="${degreeTypeInstance}" as="list" />
	</div>
	</g:hasErrors>

	<g:form method="post" class="form-horizontal" >
		<g:hiddenField name="id" value="${degreeTypeInstance?.id}" />
		<g:hiddenField name="version" value="${degreeTypeInstance?.version}" />
		<fieldset class="form">
			<g:render template="degreeTypeForm"/>
		</fieldset>
		<div class="form-actions">
			<g:actionSubmit class="btn btn-primary" action="save" value="${message(code: 'default.button.saverrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr4444.label', default: 'Update')}" />
			<g:actionSubmit class="btn btn-danger" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            <button class="btn" type="reset"><g:message code="default.button.reset.label" default="Reset" /></button>
		</div>
	</g:form>
</section>
			
</body>

</html>

degreebuilder/grails-app/views/admin/listDegreeBlockTypes.gsp
<%@ page import="degreebuilder.DegreeBlockType" %>
<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'degreeBlockType.label', default: 'DegreeBlockType')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
<section id="list-degreeBlockType" class="first">
	<table class="table table-bordered">
		<thead>
			<tr>
				<g:sortableColumn property="name" title="${message(code: 'degreeBlockType.name.label', default: 'Name')}" />
				<g:sortableColumn property="displayGroup" title="${message(code: 'degreeBlockType.displayGroup.label', default: 'Display Group')}" />
				<g:sortableColumn property="displaySeqno" title="${message(code: 'degreeBlockType.displaySeqno.label', default: 'Display Seqno')}" />
				<g:sortableColumn property="dateCreated" title="${message(code: 'degreeBlockType.dateCreated.label', default: 'Date Created')}" />
				<g:sortableColumn property="lastUpdated" title="${message(code: 'degreeBlockType.lastUpdated.label', default: 'Last Updated')}" />
			</tr>
		</thead>
		<tbody>
		<g:each in="${degreeBlockTypeInstanceList}" status="i" var="degreeBlockTypeInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
				<td><g:link action="show" id="${degreeBlockTypeInstance.id}">${fieldValue(bean: degreeBlockTypeInstance, field: "name")}</g:link></td>
				<td>${fieldValue(bean: degreeBlockTypeInstance, field: "displayGroup")}</td>
				<td>${fieldValue(bean: degreeBlockTypeInstance, field: "displaySeqno")}</td>
				<td><g:formatDate date="${degreeBlockTypeInstance.dateCreated}" /></td>
				<td><g:formatDate date="${degreeBlockTypeInstance.lastUpdated}" /></td>
			</tr>
		</g:each>
		</tbody>
	</table>
	<div class="pagination">
		<bs:paginate total="${degreeBlockTypeInstanceTotal}" />
	</div>
</section>
</body>
</html>

degreebuilder/grails-app/views/admin/listDegreeTypes.gsp
<%@ page import="degreebuilder.DegreeType" %>
<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="layout" content="kickstart" />
	<g:set var="entityName" value="${message(code: 'degreeType.label', default: 'DegreeType')}" />
	<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
<section id="list-degreeType" class="first">
	<table class="table table-bordered">
		<thead>
			<tr>
				<g:sortableColumn property="code" title="${message(code: 'degreeType.code.label', default: 'Code')}" />
				<g:sortableColumn property="desc" title="${message(code: 'degreeType.desc.label', default: 'Desc')}" />
				<g:sortableColumn property="dateCreated" title="${message(code: 'degreeType.dateCreated.label', default: 'Date Created')}" />
				<g:sortableColumn property="lastUpdated" title="${message(code: 'degreeType.lastUpdated.label', default: 'Last Updated')}" />
			</tr>
		</thead>
		<tbody>
		<g:each in="${degreeTypeInstanceList}" status="i" var="degreeTypeInstance">
			<tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
				<td><g:link action="show" id="${degreeTypeInstance.id}">${fieldValue(bean: degreeTypeInstance, field: "code")}</g:link></td>
				<td>${fieldValue(bean: degreeTypeInstance, field: "desc")}</td>
				<td><g:formatDate date="${degreeTypeInstance.dateCreated}" /></td>
				<td><g:formatDate date="${degreeTypeInstance.lastUpdated}" /></td>
			</tr>
		</g:each>
		</tbody>
	</table>
	<div class="pagination">
		<bs:paginate total="${degreeTypeInstanceTotal}" />
	</div>
</section>
</body>
</html>