degreebuilder/grails-app/controllers/degreebuilder/DegreeKeywordController.groovy
package degreebuilder

import org.springframework.dao.DataIntegrityViolationException

/**
 * DegreeKeywordController
 * A controller class handles incoming web requests and performs actions such as redirects, rendering views and so on.
 */
class DegreeKeywordController {
	def degreebuilderService
	
	static allowedMethods = [save: "POST", update: "POST", delete: "POST"]
	
    def index() {
        redirect(action: "list", params: params)
    }
	
	def list() {
		def degreeInstance = Degree.get(params.id)
		def degreeKeywordsSelected = DegreeKeyword.findAllWhere(degreeId:degreeInstance.id).keywordId

		if (!degreeInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'degree.label', default: 'Degree'), params.id])
			redirect(action: "list")
			return
		}
		
		
//		params.max = Math.min(params.max ? params.int('max') : 10, 100)
		[keywordInstanceList: Keyword.list(params), keywordInstanceTotal: Keyword.count(),degreeInstance: degreeInstance,degreeKeywordsSelected:degreeKeywordsSelected]
	}
	
	def save(){
		degreebuilderService.saveDegreeKeyWords(params)
		redirect(action:"palette",controller:"degree", id: params.degree)	
	}
	
	
	def create() {
		def degreeInstance = Degree.get(params.id)
		//println "create"
		if (!degreeInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'degree.label', default: 'Degree'), params.id])
			redirect(action: "list")
			return
		}
		[degreeInstance: degreeInstance]
				redirect(action: "list", params: params)
	}
}

degreebuilder/grails-app/views/_menu/_admin.gsp
<ul class="nav pull-right">
	<li class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
    		<i class="icon-wrench"></i>
			<g:message code="default.admin.label"/><b class="caret"></b>
		</a>
		<ul class="dropdown-menu">
			<li class="">
				<a tabindex="-1" href="#"><b>Technical Admin</b></a>
			</li>
			<g:if env="development">
			<li class="">
				<a href="${createLink(uri: '/report/list')}">
					<i class="icon-dashboard"></i>
					Admin
				</a>
			</li>
			<li class="">
				<a href="${createLink(uri: '/dbconsole')}">
					<i class="icon-dashboard"></i>
					<g:message code="default.dbconsole.label"/>
				</a>
			</li>
			</g:if>
			<li class="">
				<a href="${createLink(uri: '/systeminfo')}">
					<i class="icon-info-sign"></i>
					<g:message code="default.systeminfo.label"/>
				</a>
			</li>
			<li class="dropdown-submenu">
				<a tabindex="-1" href="#">
					<i class="icon-sitemap"></i>
					All Controller
				</a>
				<ul class="dropdown-menu">
					<li class="controller"><g:link controller="home">HomeController</g:link></li>
					<li class="divider"></li>
					<g:each var="c" in="${grailsApplication.controllerClasses.sort { it.logicalPropertyName } }">
						<g:if test="${c.logicalPropertyName != 'home'}">
							<li class="controller"><g:link controller="${c.logicalPropertyName}">${c?.fullName?.substring(c?.fullName?.lastIndexOf('.')+1)}</g:link></li>
						</g:if>
					</g:each>
				</ul>
			</li>
		</ul>
	</li>
</ul>

degreebuilder/grails-app/views/_menu/_info.gsp
<ul class="nav pull-right">
	<li class="dropdown dropdown-btn">
		
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
    		<i class="icon-info-sign"></i>
			<g:message code="default.info.label"/> <b class="caret"></b>
		</a>
		
		<ul class="dropdown-menu">
		
			<%-- Note: Links to pages without controller are redirected in conf/UrlMappings.groovy --%>
			<li class="">
				<a href="${createLink(uri: '/about')}">
					<i class="icon-info-sign"></i>
					<g:message code="default.about.label"/>
				</a>
			</li>
			<li class="">
				<a href="${createLink(uri: '/contact')}">
					<i class="icon-envelope"></i>
					<g:message code="default.contact.label"/>
				</a>
			</li>
		</ul>
	</li>
</ul>

degreebuilder/grails-app/views/_menu/_language.gsp
<g:set var="lang" value="${session.'org.springframework.web.servlet.i18n.SessionLocaleResolver.LOCALE' ?: org.springframework.web.servlet.support.RequestContextUtils.getLocale(request).toString().substring(0,2)}"/>
<g:set var="currentURL" value="${request.forwardURI}"/>

<ul class="nav secondary-nav language-dropdown pull-right">
	<li class="dropdown dropdown-btn js-language-dropdown">
		<a class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#" href="javascript:;">
			<img class="" src="${resource(plugin: 'kickstart-with-bootstrap', dir: 'images/flags',file: lang.toString()+'.png')}" />
		</a>
		<ul class="dropdown-menu dropdown-menu-dark" role="menu">

			<!-- assuming that the default locale is English -->
			<li><a class="js-language-link" title="English" data-lang-code="en" href="${currentURL+'?lang=en'}">
				<img class="" src="${resource(plugin: 'kickstart-with-bootstrap', dir: 'images/flags',file: 'en.png')}"/>
				<g:message code="language.en" default="en"/> ${currentlURL }
			</a></li>

			<li class="divider"></li>

			<!-- get list of all locales available due to an existing property-file in /grails-app/i18n (set once in Bootstrap.groovy) -->
			<g:set var="allLocales" value="${grailsApplication.config.grails.i18n.locales}"/>
			<g:each status="i" var="locale" in="${allLocales}">
				<li><a class="js-language-link" title="${message(code: 'language.'+locale, default: locale)}" data-lang-code="${locale}" href="${currentURL+'?lang='+locale}">
					<img class="" src="${resource(plugin: 'kickstart-with-bootstrap', dir: 'images/flags',file: locale+'.png')}"/>
					<g:message code="language.${locale}" default="${locale}"/>
				</a></li>
			</g:each>

		</ul>
	</li>
</ul>

degreebuilder/grails-app/views/_menu/_menubar.gsp
<div class="">
	<ul class="nav nav-tabs" data-role="listview" data-split-icon="gear" data-filter="true" >
	
<%--		<g:each status="i" var="c" in="${grailsApplication.controllerClasses.sort { it.logicalPropertyName } }">--%>
<%--			<li class="controller${params.controller == c.logicalPropertyName ? " active" : ""}">--%>
<%--				<g:link controller="${c.logicalPropertyName}" action="index">--%>
<%--					<g:message code="${c.logicalPropertyName}.label" default="${c.logicalPropertyName.capitalize()}"/>--%>
<%--				</g:link>--%>
<%--			</li>--%>
<%--		</g:each>--%>
<%--		<li><a class="senderEmail" href="${createLink(uri: '/senderEmail/list')}">SenderEmail</a></li>--%>
		 <li style="float:left;"><img src="${resource(dir: 'images', file: 'DegreeBuilder.png')}"></li>
		 <li style="float:right;">Welcome <sec:username/><g:link controller="logout">sign out</g:link></li>
	</ul>
	<a href="${resource(dir: 'docs', file: 'help.doc')}" target='_blank' title="Click here to download the help document" style="float:right;">
		Help Document <img src="${resource(dir: 'images', file: 'word.ico')}">
	</a>
</div>

degreebuilder/grails-app/views/_menu/_navbar.gsp
<div id="Navbar" class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
			</a>

			<a class="brand" href="${createLink(uri: '/')}">
				<img class="logo" src="${resource(plugin: 'kickstart-with-bootstrap', dir:'kickstart/img',file:'grails.png')}" alt="${meta(name:'app.name')}" />
				${meta(name:'app.name')}
				<small> v${meta(name:'app.version')}</small>
			</a>

       		<div class="nav-collapse">
       		
       			<ul class="nav">
<%--					<li class="dropdown">--%>
<%--						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Browse <b class="caret"></b></a>--%>
<%--						<ul class="dropdown-menu">--%>
<%--		                    <g:each var="c" in="${grailsApplication.controllerClasses.sort { it.fullName } }">--%>
<%--		                    <li class="controller">--%>
<%--		                    	<g:link controller="${c.logicalPropertyName}">--%>
<%--									<g:if test="${c.fullName.contains('HomeController')}">--%>
<%--						    		<i class="icon-home"></i>--%>
<%--									</g:if>--%>
<%--									<g:elseif test="${c.fullName.contains('DemoPageController')}">--%>
<%--						    		<i class="icon-beaker"></i>--%>
<%--									</g:elseif>--%>
<%--		                    		${c.fullName.substring(c.fullName.lastIndexOf('.')+1)}--%>
<%--		                    	</g:link>--%>
<%--		                    </li>--%>
<%--		                    </g:each>--%>
<%--						</ul>--%>
<%--					</li>--%>
				</ul>

	  			<div class="pull-left">
					<%--Left-side entries--%>
	  			</div>

	  			<div class="pull-right">
					<%--Right-side entries--%>
					<%--NOTE: the following menus are in reverse order due to "pull-right" alignment (i.e., right to left)--%>
<%--					<g:render template="/_menu/language"/>														--%>
					<g:render template="/_menu/info"/>														
					<g:render template="/_menu/user"/><!-- NOTE: the renderDialog for the "Register" modal dialog MUST be placed outside the NavBar (at least for Bootstrap 2.1.1): see bottom of main.gsp -->
					<g:render template="/_menu/admin"/>														
<%-- 					<g:render template="/_menu/search"/> --%>
	  			</div>

			</div>
			
		</div>
	</div>
</div>

degreebuilder/grails-app/views/_menu/_submenubar.gsp
<!-- 
This menu is used to show function that can be triggered on the content (an object or list of objects).
-->

<%-- Only show the "Pills" navigation menu if a controller exists (but not for home) --%>
<g:if test="${params.controller != null	&&	params.controller != ''	&&	params.controller != 'home'}">
	<ul id="Menu" class="nav nav-pills">

		<g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />

		<%-- Degree List menu item for Admin pages --%>
		<g:if test="${params.controller == 'degreeType' || params.controller == 'degreeBlockType'|| params.controller == 'keyword'}">
			<li class="${ params.action == "list" ? 'active' : '' }">
				<g:link controller="degree" action="list"><i class="icon-th-list"></i> Degree List</g:link>
			</li>				
		</g:if>
		
		<%-- List menu item for all pages --%>
		<li class="${params.action == "list" ? 'active' : '' }">
			<g:link action="list"><i class="icon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
		</li>

		<%-- New menu item for Admin pages --%>		
		<g:if test="${params.controller == 'degreeType' || params.controller == 'degreeBlockType'|| params.controller == 'keyword'}">
			<li class="${params.action == "create" ? 'active' : '' }">
				<g:link action="create"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
			</li>			
		</g:if>
		<%-- New menu item for non-Admin pages --%>
		<g:else>
			<li class="${params.action == "create" ? 'active' : '' }">
				<g:link action="palette" params="[calledFrom: 'create']"><i class="icon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
			</li>			
		</g:else>

		<%-- Show Page menu items --%>
		<g:if test="${params.action == 'show'}">
			<%-- New menu item for Degree Type pages --%>
			<g:if test="${params.controller == 'degreeType'}">		
				<li class="${params.action == "edit" ? 'active' : '' }">
					<g:link controller="degreeType" action="edit" id="${params.id}"><i class="icon-th-list"></i> Edit Degree Type</g:link>
				</li>
			</g:if>
			
			<%-- New menu item for Degree Block Type pages --%>
			<g:if test="${params.controller == 'degreeBlockType'}">		
				<li class="${params.action == "edit" ? 'active' : '' }">
					<g:link controller="degreeBlockType" action="edit" id="${params.id}"><i class="icon-th-list"></i> Edit Degree Block Type</g:link>
				</li>
			</g:if>

			<%-- New menu item for Keyword pages --%>
			<g:if test="${params.controller == 'keyword'}">		
				<li class="${params.action == "edit" ? 'active' : '' }">
					<g:link controller="keyword" action="edit" id="${params.id}"><i class="icon-th-list"></i> Edit Keyword</g:link>
				</li>
			</g:if>
			
			<%-- Copy & edit menu items for non-Admin pages --%>
			<g:if test="${params.controller != 'degreeType' && params.controller != 'degreeBlockType' && params.controller != 'keyword'}">		
				<li class="${ params.action == "palette" ? 'active' : '' }">
					<g:link action="copy" params="[calledFrom: 'copy']" id="${params.id}"><i class="icon-pencil"></i> Copy Degree</g:link>
				</li>
				
				<li class="${ params.action == "edit" ? 'active' : '' }">
					<g:link action="palette" params="[calledFrom: 'edit']" id="${params.id}"><i class="icon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
				</li>
			</g:if>
			<!-- the item is an object (not a list) -->

			<%-- Delete menu item for Admin pages --%>
			<g:if test="${params.controller == 'degreeType' || params.controller == 'degreeBlockType'|| params.controller == 'keyword'}">	
				<li class=""><g:render template="/_common/modals/deleteTextLink"/></li>
			</g:if>	
			<g:else>
			  	<li style="float:right;">
					<input type="button" class="btn btn-primary" id="print" onclick="window.print()" value="Print This Degree">
				</li>
			</g:else>
		</g:if>
		
		<g:if test="${params.action == 'edit' || params.action == 'palette'}">		
			<!-- the item is an object (not a list) -->
			<li class="${ params.action == "show" ? 'active' : '' }">
				<g:link action="show" id="${params.id}" target='_blank'></i> <g:message code="default.show.label"  args="[entityName]"/></g:link>
			</li>
			<li class="${ params.action == "edit" ? 'active' : '' }">
				<g:link controller="degreeKeyword" action="create" id="${params.id}"><i class="icon-pencil"></i>Add Keyword</g:link>
			</li>
			<g:if test="${session.isAdminUser == 'true'}">	
				<li class=""><g:render template="/_common/modals/deleteTextLink"/></li>
			</g:if>	
		</g:if>		

		<g:if test="${session.isAdminUser == 'true'}">
			<g:if test="${params.controller != 'degreeType'}">		
				<li><g:link controller="degreeType" action="list">Degree Type List</g:link></li>
			</g:if>
			<g:if test="${params.controller != 'degreeBlockType'}">	
				<li><g:link controller="degreeBlockType" action="list">Degree Block Type List</g:link></li>
			</g:if>
			<g:if test="${params.controller != 'keyword'}">	
				<li><g:link controller="keyword" action="list">Keyword List</g:link></li>
			</g:if>
			<g:if test="${params.controller != 'keyword'}">	
				<li><g:link controller="degree" action="copyDegrees">Copy Degrees</g:link></li>
			</g:if>
		</g:if>	

	</ul>
</g:if>

degreebuilder/grails-app/views/_menu/_user.gsp
<ul class="nav pull-right">
	<li class="dropdown dropdown-btn">
<%--<sec:ifNotLoggedIn>--%>

		<a class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#" href="#" tabindex="-1">
			<!-- TODO: integrate Springsource Security etc. and show User's name ... -->
    		<i class="icon-user"></i>
    		<g:message code="security.signin.label"/><b class="caret"></b>
		</a>

		<ul class="dropdown-menu" role="menu">
			<li class="form-container">
				<form action="login" method="post" accept-charset="UTF-8">
					<input style="margin-bottom: 15px;" type="text" placeholder="Username" id="username" name="username">
					<input style="margin-bottom: 15px;" type="password" placeholder="Password" id="password" name="password">
					<input style="float: left; margin-right: 10px;" type="checkbox" name="remember-me" id="remember-me" value="1">
					<label class="string optional" for="user_remember_me"> Remember me</label>
					<input class="btn btn-primary btn-block" type="submit" id="sign-in" value="Sign In">
				</form>
			</li>
			<li class="divider"></li>
			<li class="button-container">
				<!-- NOTE: the renderDialog MUST be placed outside the NavBar (at least for Bootstrap 2.1.1): see bottom of main.gsp -->
				<g:render template="/_common/modals/registerTextLink"/>
			</li>
		</ul>

<%--</sec:ifNotLoggedIn>--%>
<%--<sec:ifLoggedIn>--%>

<%--		<a class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#" href="#">--%>
<%--			<!-- TODO: Only show menu items based on permissions (e.g., Guest has no account page) -->--%>
<%--			<i class="icon-user icon-large icon-white"></i>--%>
<%--			${user.name}--%>
<%--			<g:message code="default.user.unknown.label" default="Guest"/> <b class="caret"></b>--%>
<%--		</a>--%>
<%--		<ul class="dropdown-menu" role="menu">--%>
<%--			<!-- TODO: Only show menu items based on permissions -->--%>
<%--			<li class=""><a href="${createLink(uri: '/')}">--%>
<%--				<i class="icon-user"></i>--%>
<%--				<g:message code="user.show.label"/>--%>
<%--			</a></li>--%>
<%--			<li class=""><a href="${createLink(uri: '/')}">--%>
<%--				<i class="icon-cogs"></i>--%>
<%--				<g:message code="user.settings.change.label"/>--%>
<%--			</a></li>--%>
<%--			--%>
<%--			<li class="divider"></li>--%>
<%--			<li class=""><a href="${createLink(uri: '/')}">--%>
<%--				<i class="icon-off"></i>--%>
<%--				<g:message code="security.signoff.label"/>--%>
<%--			</a></li>--%>
<%--		</ul>--%>

<%--</sec:ifLoggedIn>--%>
	</li>
</ul>

<noscript>
<ul class="nav pull-right">
	<li class="">
		<g:link controller="user" action="show"><g:message code="default.user.unknown.label"/></g:link>
	</li>
</ul>
</noscript>